const cfg=window.TEST_CONFIG,$=s=>document.querySelector(s);let bank=[],meta,quiz=[],at=0,answers=[],selected=null;
async function init(){try{const r=await fetch(cfg.data);if(!r.ok)throw Error(`HTTP ${r.status}`);({meta,questions:bank}=await r.json());$('.topics').innerHTML=meta.categories.map(c=>`<span class="topic">${c.icon} ${c.label}</span>`).join('');document.querySelectorAll('.length').forEach(b=>b.addEventListener('click',()=>start(Number(b.dataset.length))))}catch(e){$('.start').innerHTML=`<p class="support-note">${cfg.loadError}: ${e.message}</p>`}}
function shuffle(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function sample(n){if(n===500)return shuffle([...bank]);const groups=Object.fromEntries(meta.categories.map(c=>[c.id,shuffle(bank.filter(q=>q.category===c.id))]));const out=[];let round=0;while(out.length<n){for(const c of meta.categories){if(out.length<n&&groups[c.id][round])out.push(groups[c.id][round])}round++}return shuffle(out)}
function start(n){quiz=sample(n);at=0;answers=[];selected=null;$('.start').classList.add('hidden');$('.results').classList.add('hidden');$('.quiz').classList.remove('hidden');render()}
function render(){const q=quiz[at],c=meta.categories.find(x=>x.id===q.category);$('.counter').textContent=`${cfg.question} ${at+1} / ${quiz.length}`;$('.fill').style.width=`${at/quiz.length*100}%`;$('.category').textContent=`${c.icon} ${c.label}`;$('.statement').textContent=q.text;$('.scale').innerHTML=Array.from({length:10},(_,i)=>`<button class="rating" data-v="${i+1}">${i+1}</button>`).join('');$('.next').disabled=true;$('.next').textContent=at===quiz.length-1?cfg.finish:cfg.next;selected=null;document.querySelectorAll('.rating').forEach(b=>b.addEventListener('click',()=>{selected=Number(b.dataset.v);document.querySelectorAll('.rating').forEach(x=>x.classList.toggle('selected',x===b));$('.next').disabled=false}))}
$('.next').addEventListener('click',()=>{const q=quiz[at];answers.push({category:q.category,value:q.reverse?11-selected:selected});at++;at<quiz.length?render():results()});$('.quit').addEventListener('click',reset);$('.retry').addEventListener('click',reset);
function results(){const avg=answers.reduce((s,a)=>s+a.value,0)/answers.length,level=meta.levels.find(l=>avg>=l.min&&avg<l.max)||meta.levels.at(-1),pct=(avg-1)/9*100;$('.quiz').classList.add('hidden');$('.results').classList.remove('hidden');$('.score-ring').style.setProperty('--score',`${pct*3.6}deg`);$('.score-ring strong').textContent=avg.toFixed(1);$('.score-ring span').textContent=cfg.outOf;$('.level').textContent=`${level.emoji} ${level.label}`;$('.result-copy').textContent=level.desc;$('.breakdown').innerHTML=meta.categories.map(c=>{const a=answers.filter(x=>x.category===c.id);if(!a.length)return'';const v=a.reduce((s,x)=>s+x.value,0)/a.length;return`<div class="break-row"><span>${c.icon} ${c.label}</span><div class="mini-track"><div class="mini-fill" style="width:${(v-1)/9*100}%"></div></div><span>${v.toFixed(1)}</span></div>`}).join('');window.scrollTo({top:0,behavior:'smooth'})}
function reset(){$('.quiz').classList.add('hidden');$('.results').classList.add('hidden');$('.start').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}init();
